// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SampleWebAPICore.Data;
using System;

namespace SampleWebAPICore.Migrations
{
    [DbContext(typeof(PasienDataContext))]
    partial class PasienDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SampleWebAPICore.Models.Pasien", b =>
                {
                    b.Property<int>("PasienID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alamat");

                    b.Property<string>("Nama");

                    b.Property<string>("Telpon");

                    b.Property<int>("Umur");

                    b.HasKey("PasienID");

                    b.ToTable("Pasien");
                });

            modelBuilder.Entity("SampleWebAPICore.Models.Pengguna", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.HasKey("Username");

                    b.ToTable("Pengguna");
                });
#pragma warning restore 612, 618
        }
    }
}
